'use client';

import React, { useMemo } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import {
  calculateDebtHealthScore,
  getScoreCategory,
  calculateAnnualSavings,
  calculateFreedomGPS,
  calculateInterestLeak,
  calculateCashFlow,
  getWeightedAvgRate,
  formatCurrency,
} from '@/lib/calculations';
import DebtHealthScore from '@/components/dashboard/DebtHealthScore';
import DebtSummary from '@/components/dashboard/DebtSummary';
import FreedomGPS from '@/components/dashboard/FreedomGPS';
import InterestLeak from '@/components/dashboard/InterestLeak';
import PaymentPrioritizer from '@/components/dashboard/PaymentPrioritizer';
import SalaryCashFlow from '@/components/dashboard/SalaryCashFlow';

export default function DashboardPage() {
  const router = useRouter();
  const { isAuthenticated, name, mockProfile, monthlySalary, salaryDate, lastUpdated, refreshData } = useAuth();

  // Redirect if not authenticated or missing income
  if (typeof window !== 'undefined' && (!isAuthenticated || !mockProfile)) {
    router.replace('/');
    return null;
  }

  if (typeof window !== 'undefined' && monthlySalary === 0) {
    router.replace('/income');
    return null;
  }

  // Bail early during SSR or if no profile
  if (!mockProfile) return null;

  const accounts = mockProfile.debtAccounts;

  // PRD Section 3: Debt Health Score Algorithm
  const scoreBreakdown = useMemo(
    () => calculateDebtHealthScore(accounts, monthlySalary),
    [accounts, monthlySalary]
  );
  const category = useMemo(() => getScoreCategory(scoreBreakdown.score), [scoreBreakdown.score]);

  // PRD: Savings Calculation
  const annualSavings = useMemo(() => calculateAnnualSavings(accounts), [accounts]);

  // PRD RS-05: Freedom GPS
  const freedomGPS = useMemo(() => calculateFreedomGPS(accounts), [accounts]);

  // PRD RS-06: Interest Leak Report
  const interestLeak = useMemo(() => calculateInterestLeak(accounts), [accounts]);

  // PRD RS-08: Salary Day Cash Flow
  const cashFlow = useMemo(
    () => calculateCashFlow(accounts, monthlySalary, salaryDate),
    [accounts, monthlySalary, salaryDate]
  );

  // Aggregates
  const totalOutstanding = accounts.reduce((s, a) => s + a.outstanding, 0);
  const totalEMI = accounts.reduce((s, a) => s + a.emi_amount, 0);
  const avgRate = getWeightedAvgRate(accounts);

  // PDF download (PRD RS-11)
  const handleDownloadPDF = () => {
    const content = `
EXITDEBT — DEBT HEALTH REPORT
================================
Debt Health Score: ${scoreBreakdown.score}/100 (${category.label})
CIBIL Score: ${mockProfile.creditScore}

SUMMARY
-------
Total Outstanding: ${formatCurrency(totalOutstanding)}
Total EMI: ${formatCurrency(totalEMI)}/month
Average Interest Rate: ${avgRate.toFixed(1)}%
Potential Annual Savings: ${formatCurrency(annualSavings)}

DEBT ACCOUNTS
-------------
${accounts.map((a) => `${a.lender_name} | ${a.account_type} | ${formatCurrency(a.outstanding)} | ${a.interest_rate}% | EMI: ${formatCurrency(a.emi_amount)}`).join('\n')}

FREEDOM GPS
-----------
Current path: debt-free in ${freedomGPS.currentMonths} months
With restructuring: ${freedomGPS.optimizedMonths} months (${freedomGPS.monthsSaved} months sooner)

INTEREST LEAK (This Month)
--------------------------
To Principal: ${formatCurrency(interestLeak.toPrincipal)}
To Interest: ${formatCurrency(interestLeak.toInterest)}
Avoidable Interest: ${formatCurrency(interestLeak.avoidableInterest)}

Report generated by ExitDebt (https://exitdebt.in)
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `exitdebt-report-${scoreBreakdown.score}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // WhatsApp share (PRD RS-12)
  const handleWhatsAppShare = () => {
    const text = `My ExitDebt Debt Health Score: ${scoreBreakdown.score}/100 (${category.label}). I could save ${formatCurrency(annualSavings)}/year by restructuring! Check yours free at https://exitdebt.in`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  return (
    <main className="min-h-screen py-8 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header (PRD RS-13: personalization) */}
        <div className="flex items-center justify-between mb-8">
          <Link href="/" className="text-xl font-bold">
            <span className="text-text-primary">Exit</span>
            <span className="gradient-text">Debt</span>
          </Link>
          <span className="text-sm text-text-secondary">Hi, {name} 👋</span>
        </div>

        {/* RS-01: Debt Health Score with animated gauge (RS-14) */}
        <DebtHealthScore
          score={scoreBreakdown.score}
          category={category}
          creditScore={mockProfile.creditScore}
        />

        <div className="h-6" />

        {/* RS-02, RS-03, RS-04: Debt Summary */}
        <DebtSummary
          accounts={accounts}
          totalOutstanding={totalOutstanding}
          totalEMI={totalEMI}
          avgRate={avgRate}
          annualSavings={annualSavings}
        />

        <div className="h-6" />

        {/* RS-05: Freedom GPS */}
        <FreedomGPS data={freedomGPS} />

        <div className="h-6" />

        {/* RS-06: Interest Leak Report */}
        <InterestLeak data={interestLeak} />

        <div className="h-6" />

        {/* RS-07: Smart Payment Prioritizer */}
        <PaymentPrioritizer accounts={accounts} />

        <div className="h-6" />

        {/* RS-08: Salary Day Cash Flow */}
        <SalaryCashFlow data={cashFlow} />

        <div className="h-6" />

        {/* RS-11, RS-12: Share/Download */}
        <div className="glass-card p-6 text-center">
          <h3 className="text-xs font-bold text-text-muted uppercase tracking-widest mb-4">
            📊 Share Your Results
          </h3>
          <div className="flex gap-3 justify-center">
            <button
              onClick={handleDownloadPDF}
              className="px-5 py-2.5 rounded-lg border border-border text-sm font-medium text-text-primary hover:bg-bg-soft transition-colors"
            >
              📄 Download Report
            </button>
            <button
              onClick={handleWhatsAppShare}
              className="px-5 py-2.5 rounded-lg border border-border text-sm font-medium text-text-primary hover:bg-bg-soft transition-colors"
            >
              💬 Share on WhatsApp
            </button>
          </div>
        </div>

        {/* RS-15: Last updated + Refresh */}
        <div className="text-center py-8">
          <div className="flex items-center justify-center gap-2 text-sm text-text-secondary mb-2">
            <div className="h-2 w-2 rounded-full bg-success" />
            <span>
              Full access free for 3 months. Last updated:{' '}
              {lastUpdated
                ? lastUpdated.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
                : 'N/A'}
            </span>
            <button
              onClick={refreshData}
              className="text-purple hover:opacity-80 font-medium ml-2 text-xs border border-purple/20 rounded px-2 py-0.5 transition-colors"
            >
              Refresh Data
            </button>
          </div>
          <p className="text-xs text-text-muted">
            Data encrypted with AES-256 • Auto-deleted after 30 days •{' '}
            <Link href="/privacy" className="text-purple hover:underline">Privacy Policy</Link>
          </p>
        </div>
      </div>
    </main>
  );
}
